### ISSUE TITLE
There isn't actually a setup.py file here

### ISSUE THREAD

**Issue by clayote** [DaulGitHub/allure-behave#6]
Your commit log suggests you think you added a setup.py but it's not there.

**Comment by DaulGitHub** [comment]
@zacharyspector Thank you for your comment.
accidentally deleted this file

**Comment by DaulGitHub** [comment]
Please enter to the slack chat https://join.slack.com/t/allure2-behave/shared_invite/enQtNjM1MjU3NDQ5MDQ2LTg4YjdiM2JmODA2YTYyOGIxMDQwZTczMjIyZTA2MTYwNTRiNzlhNThmOTFkM2FmYjJkZDIxMTcyMTUxMTU0MTE
